---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-controller
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  minReadySeconds: 30   
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapp
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebapp
        image: ayoobnaz/java-web-app
        ports:
        - containerPort: 80	  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: javawebapp
  name: javawebapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: javawebapp
